periject/periject/todo/urls.py
from django.urls import path

from periject.todo import views

app_name = 'todo'

urlpatterns = [

    path(
        '',
        views.list_lists,
        name="lists"),

    # View reorder_tasks is only called by JQuery for drag/drop task ordering.
    path(
        'reorder_tasks/',
        views.reorder_tasks,
        name="reorder_tasks"),

    # Allow users to post tasks from outside django-todo (e.g. for filing tickets - see docs)
    path(
        'ticket/add/',
        views.external_add,
        name="external_add"),

    # Three paths into `list_detail` view
    path(
        'mine/',
        views.list_detail,
        {'list_slug': 'mine'},
        name="mine"),

    path(
        '<int:list_id>/<str:list_slug>/completed/',
        views.list_detail,
        {'view_completed': True},
        name='list_detail_completed'),

    path(
        '<int:list_id>/<str:list_slug>/',
        views.list_detail,
        name='list_detail'),

    path(
        '<int:list_id>/<str:list_slug>/delete/',
        views.del_list,
        name="del_list"),

    path(
        'add_list/',
        views.add_list,
        name="add_list"),

    path(
        'task/<int:task_id>/',
        views.task_detail,
        name='task_detail'),

    path(
        'toggle_done/<int:task_id>/',
        views.toggle_done,
        name='task_toggle_done'),

    path(
        'delete/<int:task_id>/',
        views.delete_task,
        name='delete_task'),

    path(
        'search/',
        views.search,
        name="search"),
]

periject/periject/urls.py
"""
Definition of urls for periject.
"""

from django.conf.urls import include, url
from django.contrib import admin
#from periject.account import 
from periject.account import urls
from periject.account import views
from periject.Dashboard import views
from periject.grc import views
from periject.proj import views
from periject.supplier import views
from django.urls import path
from periject.proj import urls
from periject.todo import urls
from periject.assurance import views 
#from periject.Dashboard import urls

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^account/',include('periject.account.urls',namespace='account')),
    url(r'^account/',include('django.contrib.auth.urls')),
    url(r'^dashboard/$',views.DashBoard.as_view(),name='dashboard'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    #url(r'^projects/$',views.ProjectsPage.as_view(),name='projects'),
    url(r'^suppliers/$',views.SupplierPage.as_view(),name='suppliers'),
    url(r'^grc/$',views.GRCPage.as_view(),name='grc'),
    url(r'^support/$',views.SupportPage.as_view(),name='support'),
   # url(r'session_security/', include('session_security.urls')),
   #url(r'^projects/newproject/$',views.CreateNewProject.as_view(),name='newproject'),
   #url(r'^projects/newproject/newassurance/$',views.CreateNewAssurance.as_view(),name='newassurance'),
   #url(r'^projects/newproject/newsupplier/$',views.CreateNewSupplier.as_view(),name='newsupplier'),
   #url(r'^projects/newproject/newgrc/$',views.CreateNewGRC.as_view(),name='newgrc'),  
   path('newproject/', include('periject.todo.urls', namespace="todo")),
   url(r'^assurance/$',views.AssurancePage.as_view(),name='assurance'),
]

periject/periject/todo/models.py
from __future__ import unicode_literals
import datetime

from django.conf import settings
from django.contrib.auth.models import Group
from django.db import models
from django.urls import reverse
from django.utils import timezone


class TaskList(models.Model):
    name = models.CharField(max_length=60)
   #  project_manager = models.CharField(max_length=100)
    # project_description = models.CharField(max_length=500)
    slug = models.SlugField(default='',)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

    def __str__(self):
        return self


    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Task Lists"

        # Prevents (at the database level) creation of two lists with the same slug in the same group
        unique_together = ("group", "slug")


class Task(models.Model):
    title = models.CharField(max_length=140)
    task_list = models.ForeignKey(TaskList, on_delete=models.CASCADE, null=True)
    created_date = models.DateField(default=timezone.now, blank=True, null=True)
    due_date = models.DateField(blank=True, null=True, )
    completed = models.BooleanField(default=False)
    completed_date = models.DateField(blank=True, null=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='todo_created_by', on_delete=models.CASCADE)
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL, blank=True, null=True, related_name='todo_assigned_to', on_delete=models.CASCADE)
    note = models.TextField(blank=True, null=True)
    priority = models.PositiveIntegerField()

    # Has due date for an instance of this object passed?
    def overdue_status(self):
        "Returns whether the Tasks's due date has passed or not."
        if self.due_date and datetime.date.today() > self.due_date:
            return True

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('todo:task_detail', kwargs={'task_id': self.id, })

    # Auto-set the Task creation / completed date
    def save(self, **kwargs):
        # If Task is being marked complete, set the completed_date
        if self.completed:
            self.completed_date = datetime.datetime.now()
        super(Task, self).save()

    class Meta:
        ordering = ["priority"]


class Comment(models.Model):
    """
    Not using Django's built-in comments because we want to be able to save
    a comment and change task details at the same time. Rolling our own since it's easy.
    """
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.datetime.now)
    body = models.TextField(blank=True)

    def snippet(self):
        # Define here rather than in __str__ so we can use it in the admin list_display
        return "{author} - {snippet}...".format(author=self.author, snippet=self.body[:35])

    def __str__(self):
        return self.snippet

periject/periject/todo/views.py
import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.db import IntegrityError
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.views.decorators.csrf import csrf_exempt

from periject.todo.forms import AddTaskListForm, AddEditTaskForm, AddExternalTaskForm, SearchForm
from periject.todo.models import Task, TaskList, Comment
from periject.todo.utils import (
    send_notify_mail,
    send_email_to_thread_participants,
    )


def staff_only(function):
    """
    Custom view decorator allows us to raise 403 on insufficient permissions,
    rather than redirect user to login view.
    """
    def wrap(request, *args, **kwargs):
        if request.user.is_staff:
            return function(request, *args, **kwargs)
        else:
            raise PermissionDenied

    wrap.__doc__ = function.__doc__
    wrap.__name__ = function.__name__
    return wrap


@login_required
def list_lists(request) -> HttpResponse:
    """Homepage view - list of lists a user can view, and ability to add a list.
    """

    thedate = datetime.datetime.now()
    searchform = SearchForm(auto_id=False)

    # Make sure user belongs to at least one group.
    if request.user.groups.all().count() == 0:
        messages.warning(request, "You do not yet belong to any groups. Ask your administrator to add you to one.")

    # Superusers see all lists
    if request.user.is_superuser:
        lists = TaskList.objects.all().order_by('group', 'name')
    else:
        lists = TaskList.objects.filter(group__in=request.user.groups.all()).order_by('group', 'name')

    list_count = lists.count()

    # superusers see all lists, so count shouldn't filter by just lists the admin belongs to
    if request.user.is_superuser:
        task_count = Task.objects.filter(completed=0).count()
    else:
        task_count = Task.objects.filter(completed=0).filter(task_list__group__in=request.user.groups.all()).count()

    context = {
       "lists": lists,
       "thedate": thedate,
       "searchform": searchform,
       "list_count": list_count,
       "task_count": task_count,
    }

    return render(request, 'todo/list_lists.html', context)


@staff_only
@login_required
def del_list(request, list_id: int, list_slug: str) -> HttpResponse:
    """Delete an entire list. Danger Will Robinson! Only staff members should be allowed to access this view.
    """
    task_list = get_object_or_404(TaskList, slug=list_slug)

    # Ensure user has permission to delete list. Admins can delete all lists.
    # Get the group this list belongs to, and check whether current user is a member of that group.
    # FIXME: This means any group member can delete lists, which is probably too permissive.
    if task_list.group not in request.user.groups.all() and not request.user.is_staff:
        raise PermissionDenied

    if request.method == 'POST':
        TaskList.objects.get(id=task_list.id).delete()
        messages.success(request, "{list_name} is gone.".format(list_name=task_list.name))
        return redirect('todo:lists')
    else:
        task_count_done = Task.objects.filter(task_list=task_list.id, completed=True).count()
        task_count_undone = Task.objects.filter(task_list=task_list.id, completed=False).count()
        task_count_total = Task.objects.filter(task_list=task_list.id).count()

    context = {
        "task_list": task_list,
        "task_count_done": task_count_done,
        "task_count_undone": task_count_undone,
        "task_count_total": task_count_total,
        
    }

    return render(request, 'todo/del_list.html', context)


@login_required
def list_detail(request, list_id=None, list_slug=None, view_completed=False):
    """Display and manage tasks in a todo list.
    """

    # Defaults
    task_list = None
    form = None

    # Which tasks to show on this list view?
    if list_slug == "mine":
        tasks = Task.objects.filter(assigned_to=request.user)

    else:
        # Show a specific list, ensuring permissions.
        task_list = get_object_or_404(TaskList, id=list_id)
        if task_list.group not in request.user.groups.all() and not request.user.is_staff:
            raise PermissionDenied
        tasks = Task.objects.filter(task_list=task_list.id)

    # Additional filtering
    if view_completed:
        tasks = tasks.filter(completed=True)
    else:
        tasks = tasks.filter(completed=False)

    # ######################
    #  Add New Task Form
    # ######################

    if request.POST.getlist('add_edit_task'):
        form = AddEditTaskForm(request.user, request.POST, initial={
            'assigned_to': request.user.id,
            'priority': 999,
            'task_list': task_list
        })

        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.created_date = timezone.now()
            form.save()

            # Send email alert only if Notify checkbox is checked AND assignee is not same as the submitter
            if "notify" in request.POST and new_task.assigned_to and new_task.assigned_to != request.user:
                send_notify_mail(new_task)

            messages.success(request, "New task \"{t}\" has been added.".format(t=new_task.title))
            return redirect(request.path)
    else:
        # Don't allow adding new tasks on some views
        if list_slug not in ["mine", "recent-add", "recent-complete", ]:
            form = AddEditTaskForm(request.user, initial={
                'assigned_to': request.user.id,
                'priority': 999,
                'task_list': task_list,
            })

    context = {
        "list_id": list_id,
        "list_slug": list_slug,
        "task_list": task_list,
        "form": form,
        "tasks": tasks,
        "view_completed": view_completed,
    }

    return render(request, 'todo/list_detail.html', context)


@login_required
def task_detail(request, task_id: int) -> HttpResponse:
    """View task details. Allow task details to be edited. Process new comments on task.
    """

    task = get_object_or_404(Task, pk=task_id)
    comment_list = Comment.objects.filter(task=task_id)

    # Ensure user has permission to view task. Admins can view all tasks.
    # Get the group this task belongs to, and check whether current user is a member of that group.
    if task.task_list.group not in request.user.groups.all() and not request.user.is_staff:
        raise PermissionDenied

    # Save submitted comments
    if request.POST.get('add_comment'):
        Comment.objects.create(
            author=request.user,
            task=task,
            body=request.POST['comment-body'],
        )

        send_email_to_thread_participants(
            task, request.POST['comment-body'], request.user,
            subject='New comment posted on task "{}"'.format(task.title))
        messages.success(request, "Comment posted. Notification email sent to thread participants.")

    # Save task edits
    if request.POST.get('add_edit_task'):
        form = AddEditTaskForm(request.user, request.POST, instance=task, initial={'task_list': task.task_list})

        if form.is_valid():
            form.save()
            messages.success(request, "The task has been edited.")
            return redirect('todo:list_detail', list_id=task.task_list.id, list_slug=task.task_list.slug)
    else:
        form = AddEditTaskForm(request.user, instance=task, initial={'task_list': task.task_list})

    # Mark complete
    if request.POST.get('toggle_done'):
        results_changed = toggle_done([task.id, ])
        for res in results_changed:
            messages.success(request, res)

        return redirect('todo:task_detail', task_id=task.id,)

    if task.due_date:
        thedate = task.due_date
    else:
        thedate = datetime.datetime.now()

    context = {
        "task": task,
        "comment_list": comment_list,
        "form": form,
        "thedate": thedate,
    }

    return render(request, 'todo/task_detail.html', context)


@csrf_exempt
@login_required
def reorder_tasks(request) -> HttpResponse:
    """Handle task re-ordering (priorities) from JQuery drag/drop in list_detail.html
    """
    newtasklist = request.POST.getlist('tasktable[]')
    if newtasklist:
        # First task in received list is always empty - remove it
        del newtasklist[0]

        # Re-prioritize each task in list
        i = 1
        for id in newtasklist:
            task = Task.objects.get(pk=id)
            task.priority = i
            task.save()
            i += 1

    # All views must return an httpresponse of some kind ... without this we get
    # error 500s in the log even though things look peachy in the browser.
    return HttpResponse(status=201)


@staff_only
@login_required
def add_list(request) -> HttpResponse:
    """Allow users to add a new todo list to the group they're in.
    """

    if request.POST:
        form = AddTaskListForm(request.user, request.POST)
        if form.is_valid():
            try:
                newlist = form.save(commit=False)
                newlist.slug = slugify(newlist.name)
                newlist.save()
                messages.success(request, "A new list has been added.")
                return redirect('todo:lists')

            except IntegrityError:
                messages.warning(
                    request,
                    "There was a problem saving the new list. "

periject/periject/todo/templates/todo/add_list.html
{% extends "todo/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}Create a new project{% endblock %}
{% block content %}

  <h2>Add a project</h2>

  <form action="" method="post">
    {% csrf_token %}

<div class="container">
  <div class="row">
    <div class="col-sm">
    <div class="form-group">
      <label for="id_name">Project title</label>
      <input type="text" class="form-control" id="id_name" name="name" aria-describedby="inputNameHelp" placeholder="">
      <small id="inputNameHelp" class="form-text text-muted">This is the name of the project.</small>
    </div>
</div>
    <div class="col-sm">
      <div class="form-group">
      <label for="id_name">Project manager</label>
      <input type="text" class="form-control" id="id_name" name="projectmanager1" aria-describedby="inputNameHelp" placeholder="">
      <small id="inputNameHelp" class="form-text text-muted"></small>
    </div>
    </div>
</div>
<div class="form-group">
      <label for="id_name">Project description</label>
      <input type="text" class="form-control" id="id_name" name="projectdescription1" aria-describedby="inputNameHelp" placeholder="">
      <small id="inputNameHelp" class="form-text text-muted">Please provide a breif project description.</small>
</div>
    <div class="form-group">
      <label for="id_group">Project type</label>
      {{form.group}}
    </div>
    <button type="submit" class="btn btn-primary">Next</button>
  </form>
</div>
{% endblock %}

periject/periject/todo/templates/todo/add_task_external.html
{% extends "todo/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}File Ticket{% endblock %}

{% block content %}

  <h2>{{ task }}</h2>

  <form action="" method="POST">
    {% csrf_token %}

    <h3>File Trouble Ticket</h3>
    <p>
      Have a support issue? Use this form to report the difficulty - we'll get right back to you.
    </p>

    {% if form.errors %}
      {% for error in form.errors %}
        <ul class="errorlist">
          <li>
            <strong>The {{ error|escape }} field is required.</strong>
          </li>
        </ul>
      {% endfor %}
    {% endif %}

    <form action="" name="add_task" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_title" name="title">Subject</label>
          <input type="text" class="form-control" id="id_title" name="title" required placeholder="Our spaceship doesn't go"
            value="{% if form.title.value %}{{ form.title.value }}{% endif %}">
        </div>
        <div class="form-group">
          <label for="id_note">Description</label>
          <textarea class="form-control" id="id_note" name="note" rows="5"
            aria-describedby="inputNoteHelp">{% if form.note.value %}{{ form.note.value }}{% endif %}</textarea>
          <small id="inputNoteHelp" class="form-text text-muted">
            Describe the issue. Please include essential details.
          </small>
        </div>

        <input type="hidden" id="id_priority" name="priority" value="50">
        <p><input type="submit" class="btn btn-primary" name="add_task" value="Submit"></p>
    </form>

{% endblock %}

periject/periject/todo/templates/todo/base.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extrahead %}
	<!-- CSS and JavaScripts for django-todo -->
	<link rel="stylesheet" type="text/css" href="{% static 'todo/css/styles.css' %}" />
{% endblock extrahead %}

periject/periject/todo/templates/todo/del_list.html
{% extends "todo/base.html" %}
{% block title %}Delete list{% endblock %}

{% block content %}
  {% if user.is_staff %}
  <h1>Delete entire list: {{ task_list.name }} ?</h1>

  <p>Category tally:</p>

  <ul>
    <li>Incomplete: {{ task_count_undone }} </li>
    <li>Complete: {{ task_count_done }} </li>
    <li>
      <strong>Total: {{ task_count_total }}</strong>
    </li>
  </ul>

  <p> ... all of which will be irretrievably
    <strong>blown away</strong>. Are you sure you want to do that?</p>

  <form action="" method="post" accept-charset="utf-8">
    {% csrf_token %}
    <input type="hidden" name="task_list" value="{{ task_list.id }}">
    <p>
      <a href="{% url 'todo:list_detail' task_list.id task_list.slug %}" class="btn btn-success">Return to list: {{ task_list.name }}</a>
      <input type="submit" name="delete-confirm" value="Do it! &rarr;" class="btn btn-danger">
    </p>
  </form>


{% else %}
  <p>Sorry, you don't have permission to delete lists. Please contact your group administrator.</p>
{% endif %} {% endblock %}

periject/periject/todo/templates/todo/list_detail.html
{% extends "todo/base.html" %}
{% load staticfiles %}

{% block title %}Todo List: {{ task_list.name }}{% endblock %}

{% block content %}

  {% if list_slug != "mine" %}
<div class="container">
<div class="row">
  <div class="col">Project Name: {{ task_list.name }} </div>
  <div class="col">Project Manager: {{ task_list.projectmanager1 }} </div>
  <div class="w-100"></div>
  <div class="col">Project Description: {{ task_list.projectdescription1 }} </div>

</div>
</div>

    <button class="btn btn-primary" id="AddTaskButton" type="button"
      data-toggle="collapse" data-target="#AddEditTask">Add Task</button>

    {# Task edit / new task form #}
    {% include 'todo/include/task_edit.html' %}
    <hr />
  {% endif %}

  {% if tasks %}
    {% if list_slug == "mine" %}
      <h1>Tasks assigned to me (in all groups)</h1>
    {% else %}
      <h1>{{ view_completed|yesno:"Completed tasks, Tasks" }} in "{{ task_list.name }}"</h1>
      <p><small><i>In workgroup "{{ task_list.group }}" - drag rows to set priorities.</i></small></p>
    {% endif %}

      <table class="table" id="tasktable">
        <tr class="nodrop">
          <th>Task</th>
          <th>Created</th>
          <th>Due on</th>
          <th>Owner</th>
          <th>Assigned</th>
          <th>Mark</th>
        </tr>

        {% for task in tasks %}
          <tr id="{{ task.id }}">
            <td>
                <a href="{% url 'todo:task_detail' task.id %}">{{ task.title|truncatewords:10 }}</a>
            </td>
            <td>
                {{ task.created_date|date:"m/d/Y" }}
            </td>
            <td>
              <span {% if task.overdue_status %}class="overdue"{% endif %}>
                {{ task.due_date|date:"m/d/Y" }}
              </span>
            </td>
            <td>
              {{ task.created_by }}
            </td>
            <td>
              {% if task.assigned_to %}{{ task.assigned_to }}{% else %}Anyone{% endif %}
            </td>
            <td>
                <a href="{% url "todo:task_toggle_done" task.id %}" class="btn btn-info btn-sm">
                  {% if view_completed %}
                    Not Done
                  {% else %}
                    Done
                  {% endif %}
                </a>
              </td>
          </tr>
        {% endfor %}
      </table>

      {% include 'todo/include/toggle_delete.html' %}

  {% else %}
    <h4>No tasks on this list yet (add one!)</h4>
    {% include 'todo/include/toggle_delete.html' %}

  {% endif %}

{% endblock %}

{% block extra_js %}
  <script src="{% static 'todo/js/jquery.tablednd_0_5.js' %}" type="text/javascript"></script>

  <script type="text/javascript">
    function order_tasks(data) {
      // The JQuery plugin tableDnD provides a serialize() function which provides the re-ordered
      // data in a list. We pass that list as an object ("data") to a Django view
      // to save new priorities on each task in the list.
      $.post("{% url 'todo:reorder_tasks' %}", data, "json");
      return false;
    };

    $(document).ready(function() {
      // Initialise the task table for drag/drop re-ordering
      $("#tasktable").tableDnD();

      $('#tasktable').tableDnD({
        onDrop: function(table, row) {
          order_tasks($.tableDnD.serialize());
        }
      });

    });

    // When adding a task, change the text of the Add Task button
    function handleClick()
    {
        console.log(this.innerHTML);
        this.innerHTML = (this.innerHTML == 'Add Task' ? 'Cancel' : 'Add Task');
    }
    document.getElementById('AddTaskButton').onclick=handleClick;
  </script>
{% endblock extra_js %}

periject/periject/todo/templates/todo/list_lists.html
{% extends "todo/base.html" %}

{% block title %}{{ list_title }} Todo Lists{% endblock %}

{% block content %}
  <h1>Project overview</h1>

  <p>{{ task_count }} tasks in {{ list_count }} projects {{ list_count|pluralize }}</p>

  {% regroup lists by group as section_list %}
  {% for group in section_list %}
    <h3> {{ group.grouper }}</h3>
    <ul class="list-group mb-4">
      {% for task in group.list %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <a href="{% url 'todo:list_detail' task.id task.slug %}">{{ task.name }}</a>
        <span class="badge badge-primary badge-pill">{{ task.task_set.count }}</span>
      </li>
      {% endfor %}
    </ul>
  {% endfor %}

  <div class="mt-3">
    
    {% if user.is_staff %}
      <a href="{% url 'todo:add_list' %}" class="btn btn-primary">Start a new project</a>
    {% else %}
      <a href="" class="btn btn-primary disabled">You don't have the required permissions, please speak to your admin</a>
    {% endif %}
      
  </div>

{% endblock %}

periject/periject/todo/templates/todo/search_results.html
{% extends "todo/base.html" %}

{% block title %}Search results{% endblock %}
{% block content_title %}<h2 class="page_title">Search</h2>{% endblock %}

{% block content %}
  {% if found_tasks %}
  <h2>{{found_tasks.count}} search results for term: "{{ query_string }}"</h2>
  <div class="post_list">
    {% for f in found_tasks %}
    <p>
      <strong>
        <a href="{% url 'todo:task_detail' f.id %}">{{ f.title }}</a>
      </strong>
      <br />
      <span class="minor">
        In list:
        <a href="{% url 'todo:list_detail' f.task_list.id f.task_list.slug %}">
          {{ f.task_list.name }}
        </a>
        <br /> Assigned to: {% if f.assigned_to %}{{ f.assigned_to }}{% else %}Anyone{% endif %}
        <br /> Complete: {{ f.completed|yesno:"Yes,No" }}
      </span>
    </p>
    {% endfor %}
  </div>
  {% else %}
    <h2> No results to show, sorry.</h2>
  {% endif %}
{% endblock %}

periject/periject/todo/templates/todo/task_detail.html
{% extends "todo/base.html" %}

{% block title %}Task:{{ task.title }}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-8">
      <h3 class="card-title">{{ task.title }}</h3>
      {% if task.note %}
        <p class="card-text">{{ task.note|safe|urlize|linebreaks }}</p>
      {% endif %}
    </div>

    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item">
          <form action="" method="post">
            {% csrf_token %}

            <button class="btn btn-sm btn-primary" id="EditTaskButton" type="button"
            data-toggle="collapse" data-target="#AddEditTask">Edit Task</button>

            <a href="{% url "todo:task_toggle_done" task.id %}" class="btn btn-info btn-sm">
              {% if task.completed %} Mark Not Done {% else %} Mark Done {% endif %}
            </a>

            <a href="{% url "todo:delete_task" task.id %}" class="btn btn-danger btn-sm">Delete</a>
          </form>
        </li>
        <li class="list-group-item">
          <strong>Assigned to:</strong>
          {% if task.assigned_to %} {{ task.assigned_to.get_full_name }} {% else %} Anyone {% endif %}
        </li>
        <li class="list-group-item">
          <strong>Reported by:</strong> {{ task.created_by.get_full_name }}
        </li>
        <li class="list-group-item">
          <strong>Due date:</strong> {{ task.due_date }}
        </li>
        
        {% if task.completed %}
          <li class="list-group-item">
            <strong>Completed on:</strong> {{ task.completed_date}}
          </li>
        {% else %}
          <li class="list-group-item">
            <strong>Completed:</strong> {{ task.completed|yesno:"Yes,No" }}
          </li>
        {% endif %}
          
        <li class="list-group-item">
          <strong>In list:</strong>
          <a href="{% url 'todo:list_detail' task.task_list.id task.task_list.slug %}">
            {{ task.task_list }}
          </a>
        </li>
      </ul>
    </div>
  </div>

  <div id="TaskEdit">
    {# Task edit / new task form #}
    {% include 'todo/include/task_edit.html' %}
  </div>

  <h5>Add comment</h5>
  <form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
      <textarea class="form-control" name="comment-body" rows="3"></textarea>
    </div>
    <input class="btn btn-sm btn-primary" type="submit" name="add_comment" value="Add Comment">
  </form>

  <div class="task_comments mt-4">
    {% if comment_list %}
      <h5>Comments on this task</h5>
      {% for comment in comment_list %}
        <p>
          <strong>{{ comment.author.first_name }}
            {{ comment.author.last_name }},
            {{ comment.date|date:"F d Y P" }}
          </strong>
        </p>
        {{ comment.body|safe|urlize|linebreaks }}
      {% endfor %}
    {% else %}
        <h5>No comments (yet).</h5>
    {% endif %}
  </div>

{% endblock %}